model_short: 'llama'
task_name: 'verb-agreement'

dataset: 
  train: cache/llama/verb-agreement_test/
  test: cache/llama/verb-agreement_train/

mdl:
  batch_size: 16
  probe_type: "mlp"      # "mlp", "linear", "multilinear"
  # probe_hidden_size: only save hidden size as a list, as the input and output sizes are inferred. Only valid for mlp and multilinear probes. 
  probe_hidden_size: [16]
  optimizer: "adamw"     # "adamw", "adam", "sgd"
  train_epochs: 10
  lr: 1e-3
  seed: 42
  early_stopping_gap: 3

out_dir: ${calc_path:${model_short}, ${task_name}, ${mdl.probe_hidden_size}, ${mdl.seed}}

hydra:
  run:
    dir: ${out_dir}
